---
title: "p8105_hw2_anh2179"
author: Amitra Hoq
output: github_document
date: "2026-10-02"
---

## Problem 0
```{r}
library(tidyverse)
library(readxl)
```


## Problem 1
```{r}
transit_df = read_csv("NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |>
  janitor::clean_names() |>
  select(line,station_name,station_latitude,station_longitude,route1:route11,
         entry,vending,entrance_type,ada) |>
  mutate(entry = recode_values(entry,"YES" ~ TRUE,"NO" ~ FALSE)
         ) |>
  mutate(
    across(route1:route11, as.character)
  )
```



```{r}
transit_df |>
  distinct(station_name, line) |>
  nrow()

transit_df |>
  filter(ada == TRUE) |>
  distinct(station_name, line) |>
  nrow()

transit_df |>
  filter(vending == "NO") |>
  summarize(
    proportion_entry = mean(entry)
  )
```
```{r}
transit_tidy = 
  transit_df |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name",
    values_drop_na = TRUE
  )
    

transit_tidy |>
  filter(route_name == "A") |>
  distinct(station_name, line) |>
  nrow()

transit_tidy |>
  filter(
    route_name == "A",
    ada == TRUE
  ) |>
  distinct(station_name, line) |>
  nrow()

```

## Problem 2

```{r}
mr_trash =
  read_excel(
    "202509 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N710"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel"
  )
```


```{r}
professor_trash =
  read_excel(
    "202509 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M135"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    trash_wheel = "Professor Trash Wheel"
  )
```


```{r}
gwynnda =
  read_excel(
    "202509 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynns Falls Trash Wheel",
    range = "A2:L352"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    trash_wheel = "Gwynnda"
  )
```

```{r}
trash_wheel_df =
  bind_rows(
    mr_trash,
    professor_trash,
    gwynnda
  )

nrow(trash_wheel_df)


```


```{r}
professor_weight =
  trash_wheel_df |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  summarize(
    total_weight = sum(weight_tons, na.rm = TRUE)
  ) |>
  pull(total_weight)

professor_weight
```

```{r}
gwynnda_cigarettes =
  trash_wheel_df |>
  filter(
    trash_wheel == "Gwynnda",
    month == "June",
    year == 2022
  ) |>
  summarize(
    total_cigarette_butts = sum(cigarette_butts, na.rm = TRUE)
  ) |>
  pull(total_cigarette_butts)

gwynnda_cigarettes


```

## Problem 3

```{r}
mci_baseline =read_csv("MCI_baseline.csv",
    skip = 1,
    na = "."
  ) |>
  janitor::clean_names() |>
  mutate(
    sex = case_match(
      sex,
      1 ~ "Male",
      0 ~ "Female"
    ),
    sex = as.factor(sex),
    apoe4 = case_match(
      apoe4,
      1 ~ "Carrier",
      0 ~ "Non-carrier"
    ),
    apoe4 = as.factor(apoe4)
  ) |>
  filter(
    is.na(age_at_onset) | age_at_onset > current_age
  )

mci_baseline
dim(mci_baseline)
```

```{r}
mci_baseline |>
  summarize(
    developed_mci = sum(!is.na(age_at_onset))
  )
```

```{r}
mci_baseline |>
  summarize(
    average_age = mean(current_age)
  )
```

```{r}
mci_baseline |>
  filter(sex == "Female") |>
  summarize(
    proportion_apoe4 = mean(apoe4 == "Carrier")
  )
```

```{r}
amyloid_df =
  read_csv("mci_amyloid.csv",
    skip = 1,
    na = "Na"
  ) |>
  janitor::clean_names() |>
  pivot_longer(
    baseline:time_8,
    names_to = "visit",
    values_to = "amyloid_42_40"
  ) |>
  mutate(
    visit = case_match(
      visit,
      "baseline" ~ 0,
      "time_2" ~ 2,
      "time_4" ~ 4,
      "time_6" ~ 6,
      "time_8" ~ 8
    )
  ) |>
  drop_na(amyloid_42_40)

amyloid_df
dim(amyloid_df)
n_distinct(amyloid_df$study_id)
```

```{r}
baseline_only =
  mci_baseline |>
  filter(!(id %in% amyloid_df$study_id)) |>
  distinct(id)

print(baseline_only)
```
```{r}
amyloid_only =
  amyloid_df |>
  filter(!(study_id %in% mci_baseline$id)) |>
  distinct(study_id)

print(amyloid_only)

```
```{r}
mci_df =
  inner_join(
    mci_baseline,
    amyloid_df,
    by = c("id" = "study_id")
  )

mci_df
dim(mci_df)
n_distinct(mci_df$id)
```

