p8105_hw2_anh2179
================
Amitra Hoq
2026-10-02

# Problem 0

``` r
library(tidyverse)
library(readxl)
```

# Problem 1

## Importing and Cleaning NYC Transit Dataset

``` r
transit_df = 
  read_csv("NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
  col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) |>
  
  janitor::clean_names() |>
  select(
    line,station_name,station_latitude,station_longitude,starts_with("route"),
         entry,vending,entrance_type,ada) |>
  mutate(entry = recode_values(entry,"YES" ~ TRUE,"NO" ~ FALSE))
dim(transit_df)
```

    ## [1] 1868   19

### Paragraph about NYC Transit Dataset

This dataset describes entrances and exits at New York City subway
stations. It includes each station’s line, name, and location (latitude
and longitude), the routes it serves (route1–route11), and details about
each entrance: whether it allows entry, whether it has a vending
machine, its entrance type, and whether it is ADA compliant. I imported
the data, cleaned the variable names, and kept only the columns needed
for later parts of this problem. I then converted entry from yes/no to a
logical variable. I decided to also denote route8–route11 as characters
so they match route1–route7. The resulting dataset has 1,868 rows and 19
columns. The data is not tidy. Route number and route name should each
be a single variable, but they are spread across 11 columns.

## Questions about NYC Transit Data

``` r
# How many distinct stations are there? 
transit_df |>
  select(station_name, line) |>
  distinct() |>
  nrow()
```

    ## [1] 465

``` r
# How many stations are ADA compliant?
transit_df |>
  filter(ada == TRUE) |>
  select(station_name, line) |>
  distinct() |>
  nrow()
```

    ## [1] 84

``` r
# What proportion of station entrances / exits without vending allow entrance?
transit_df |>
  filter(vending == "NO") |>
  pull(entry) |>
  mean()
```

    ## [1] 0.3770492

## Reformatting NYC Transit Data

``` r
transit_tidy = 
  transit_df |>
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route_name",)
```

## Questions about Reformatting NYC Transit Data

``` r
# How many distinct stations serve the A train?
transit_tidy |>
  filter(route_name == "A") |>
  select(station_name, line, route_name) |>
  distinct() |>
  nrow()
```

    ## [1] 60

``` r
# Of the stations that serve the A train, how many are ADA compliant?
transit_tidy |>
  filter(route_name == "A",ada == TRUE) |> 
  select(station_name, line, ada, route_name) |>
  distinct() |>
  nrow()
```

    ## [1] 17

# Problem 2

## Importing, Cleaning, Organizing and Combining Trash Wheel Datasets

``` r
mr_trash_df =
  read_excel(
    "202610 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N743") |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    year= as.numeric(year), 
    plastic_bottles = as.double(plastic_bottles),
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel")

professor_trash =
  read_excel(
    "202610 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M140") |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    year= as.numeric(year),
    plastic_bottles = as.double(plastic_bottles),
    trash_wheel = "Professor Trash Wheel")
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `plastic_bottles = as.double(plastic_bottles)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

``` r
gwynnda =
  read_excel(
    "202610 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynnda the Good Wheel of the W",
    range = "A2:L395"
    ) |>
  janitor::clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    year= as.numeric(year),
    plastic_bottles = as.double(plastic_bottles),
    trash_wheel = "Gwynnda"
    )

trash_wheel_df = bind_rows(mr_trash_df,professor_trash,gwynnda)
```

### Paragraph about Trash Wheel Data

The combined `trash_wheel_df` dataset consists of 1269 observations and
includes data from 2014 through 2026. Some key variables include `year`,
`sports_balls`, which was rounded and converted to an integer variable,
and `plastic_bottles`, which is stored as a double variable. Given the
data, the total weight of trash collected by Professor Trash Wheel is
294.96 tons. The total number of cigarette butts collected by Gwynnda in
June of 2022 is 1.812^{4}.

# Problem 3

## Import, Clean, and Tidy Baseline Demographics

``` r
mci_baseline=
  read_csv("MCI_baseline.csv", show_col_types = FALSE, 
    skip = 1,
    na = c(".", ",","NA")) |>
  janitor::clean_names() |>
  mutate(sex = recode_values(sex,1 ~ "Male",0 ~ "Female"),
         apoe4 = recode_values(apoe4,1 ~ "Carrier",0 ~ "Non-carrier")) |>
  filter(is.na(age_at_onset) | age_at_onset > current_age)
mci_baseline
```

    ## # A tibble: 479 × 6
    ##       id current_age sex    education apoe4       age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>              <dbl>
    ##  1     1        63.1 Female        16 Carrier             NA  
    ##  2     2        65.6 Female        20 Carrier             NA  
    ##  3     3        62.5 Male          16 Carrier             66.8
    ##  4     4        69.8 Female        16 Non-carrier         NA  
    ##  5     5        66   Male          16 Non-carrier         68.7
    ##  6     6        62.5 Male          16 Non-carrier         NA  
    ##  7     7        66.5 Male          18 Non-carrier         74  
    ##  8     8        67.2 Female        18 Non-carrier         NA  
    ##  9     9        66.7 Female        16 Non-carrier         NA  
    ## 10    10        64.1 Female        18 Non-carrier         NA  
    ## # ℹ 469 more rows

``` r
dim(mci_baseline)
```

    ## [1] 479   6

### Paragraph about important steps about tidying data

To import the baseline data, we skip the first row of the CSV because it
holds variable descriptions, not data. We treat `.` and `NA` as missing
values, which lets `age_at_onset` be read as numeric. We clean the
variable names with `janitor::clean_names()`. We then recode `sex` (1 =
Male, 0 = Female) and `apoe4` (1 = Carrier, 0 = Non-carrier) from
numeric codes to labeled categories, so they are not treated as numbers.
To apply the inclusion criteria, we keep participants who never
developed MCI (missing `age_at_onset`) and those whose onset came after
their baseline age. Participants whose onset was at or before baseline
already had MCI when they entered the study, so they are removed. The
cleaned dataset has 479 rows and 6 columns: id, current_age, sex,
education, apoe4, age_at_onset. In total, 483 participants were
recruited, and 479 remain after applying the inclusion criteria. Of
these, 93 developed MCI during follow-up. The average baseline age is
65.0286013 years. Among women in the study, the proportion who are APOE4
carriers is 0.3.

``` r
mci_baseline |>
  summarize(
    developed_mci = sum(!is.na(age_at_onset))
  )
```

    ## # A tibble: 1 × 1
    ##   developed_mci
    ##           <int>
    ## 1            93

``` r
mci_baseline |>
  summarize(
    average_age = mean(current_age)
  )
```

    ## # A tibble: 1 × 1
    ##   average_age
    ##         <dbl>
    ## 1        65.0

``` r
mci_baseline |>
  filter(sex == "Female") |>
  summarize(
    proportion_apoe4 = mean(apoe4 == "Carrier")
  )
```

    ## # A tibble: 1 × 1
    ##   proportion_apoe4
    ##              <dbl>
    ## 1              0.3

## Import, clean, and tidy the dataset of longitudinally observed biomarker values

``` r
amyloid_df =
  read_csv("mci_amyloid.csv",
    skip = 1,
    na = c("Na", ".", ",")
  ) |>
  janitor::clean_names() |>
  rename(
    id = study_id,
    baseline_years = baseline
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
amyloid_df
```

    ## # A tibble: 487 × 6
    ##       id baseline_years time_2      time_4      time_6      time_8     
    ##    <dbl> <chr>          <chr>       <chr>       <chr>       <chr>      
    ##  1     1 0.1105487      NA          0.109325197 0.104756131 0.107257697
    ##  2     2 0.107481183    0.109157373 0.109457839 0.105729713 0.10661845 
    ##  3     3 0.106087034    0.108744509 0.106065035 NA          0.106152357
    ##  4     4 0.109251358    0.108699686 0.110540386 0.107476797 0.111212209
    ##  5     5 0.107950408    0.112273883 0.115139677 0.106606054 0.106052066
    ##  6     6 0.112426974    0.112853415 0.11143945  0.110279277 0.114982747
    ##  7     7 0.112246391    NA          0.104251905 0.112485583 0.112055612
    ##  8     8 0.109563372    0.109470828 NA          0.108742168 0.110268552
    ##  9     9 0.112101884    0.109781199 0.108832888 NA          NA         
    ## 10    10 0.1116094      0.111592149 NA          NA          0.110051296
    ## # ℹ 477 more rows

``` r
dim(amyloid_df)
```

    ## [1] 487   6

### comment on the steps on the import process and the features of the dataset.

## Checking to see if

``` r
mci_baseline |>
  anti_join(amyloid_df, by = "id") |>
  nrow()
```

    ## [1] 8

``` r
 amyloid_df |>
  anti_join(mci_baseline, by = "id") |>
  nrow()
```

    ## [1] 16

### Paragraph on findings

## Combine the demographic and biomarker datasets so that only participants who appear in both datasets are retained

``` r
mci_df =
  inner_join( mci_baseline,amyloid_df,by = "id")
```

### Paragraph

## Exporting CSV to directory

``` r
write_csv(mci_df,"mci_data.csv")
```
